@startuml
TradeUsecase -> AnalyzeUsecase : 次のルートに行くのが良いか、ベース通貨に戻るのが良いか判定
AnalyzeUsecase -> TickerRepository : 価格表を取得
TickerRepository -> AnalyzeUsecase : 価格表
AnalyzeUsecase -> TradeUsecase : 判定結果
alt ベース通貨に戻る
    TradeUsecase -> TickerRepository : 取引作成
    loop 約定するまで
        TradeUsecase -> TickerRepository : 約定を確認
    end
else
    TradeUsecase -> TickerRepository : 取引作成
    loop 約定するまで
        TradeUsecase -> TickerRepository : 約定を確認
        alt タイムアウト
            TradeUsecase -> TradeUsecase : ベース通貨に戻る
            break
        end
    end
end
@enduml
