@startuml
actor Exchange
Exchange -> Arbitrader : 価格の変動を通知
Arbitrader -> MarketAnalyzer : 利益見込みのある取引ペアを検索
Arbitrader <-- MarketAnalyzer : 取引ペア
alt 利益見込みのある取引ペアなし
    Arbitrader -> Arbitrader : 終了
    destroy Arbitrader
else 利益見込みのある取引ペアあり
    Arbitrader -> Exchange : 取引
end
@enduml